version: 0.2

phases:

  install: 
    commands:
      - go get github.com/golang/lint/golint
      - go get github.com/gruntwork-io/terratest/modules/terraform

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # install dependencies
      - dep ensure

  build:
    commands:

      # Run basic FT test
      - go test test/terraform_basic_example_test.go

artifacts:
  files:
    - buildspec.yml
