version: 0.2

phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

  build:
    commands:

      # Run basic FT test
      - go test terraform_basic_example_test.go

artifacts:
  files:
    - buildspec.yml
